In [ ]:
NumPy

NumPy is the fundamental package for scientific computing with Python
http://www.numpy.org/


In [2]:
import numpy as np

In [ ]:
#Array Creation
#1 Create Arrays from list

In [22]:
marks_list = [89.00, 67.5, 95.3]

In [23]:
#1-D array
n1 = np.array(marks_list)
print(n1, type(n1))

[89.  67.5 95.3] <class 'numpy.ndarray'>


In [8]:
#2-D array
n2 = np.array( [[1,4,9], [4,-5, 0], [33, -8, 1]]
       
                )
print(n2, type(n2))

[[ 1  4  9]
 [ 4 -5  0]
 [33 -8  1]] <class 'numpy.ndarray'>


In [ ]:
#Basic Concepts
#np.ndarray
#np.dtype

In [ ]:
#inspecting properties of arrays
# a.size - Returns  number of elements in arr
# a.shape - Returns dimensions of array a (rows,columns)
# a.dtype - Returns type of elements in array a 
# a.astype(dtype) - Convert array a elements to type dtype
# a.tolist() - Convert array a  to a Python list



In [10]:
print(n2)
print(n2.size)
print(n2.shape)
print(n2.dtype)
print(n2.astype(str))

[[ 1  4  9]
 [ 4 -5  0]
 [33 -8  1]]
9
(3, 3)
int32
[['1' '4' '9']
 ['4' '-5' '0']
 ['33' '-8' '1']]


In [ ]:
#special arrays
#zeros, ones, eyes

In [12]:

z1 = np.zeros((4))
print(z1,type(z1))

[0. 0. 0. 0.] <class 'numpy.ndarray'>


In [13]:
z2 = np.ones(4)
print(z2,type(z2))

[1. 1. 1. 1.] <class 'numpy.ndarray'>


In [14]:
z3 = np.eye(5)  #   I
print(z3, type(z3))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] <class 'numpy.ndarray'>


In [16]:
#Evenly spaced 5 values between 0 and 100
p1 = np.linspace(0,100,5)
print(p1, type(p1))

[  0.  25.  50.  75. 100.] <class 'numpy.ndarray'>


In [15]:
#array in the range between 0 to 30 in step of 4
p2 = np.arange(0,31,3)   #range(10) python
print(p2, type(p2))

[ 0  3  6  9 12 15 18 21 24 27 30] <class 'numpy.ndarray'>


In [16]:
#empty array of any given shape
p3 = np.empty((3,4))
print(p3,type(p3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>


In [21]:
#fill an array of given shape and fill value
p4 = np.full((3,4),9)
print(p4, type(p4))

[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]] <class 'numpy.ndarray'>


In [17]:
#np.random.rand(5,3) - 5x3 array of random floats between 0-1
p5 = np.random.rand(5,3)
print(p5,type(p5))

[[0.23551601 0.17622231 0.06647993]
 [0.76127865 0.95175749 0.00474444]
 [0.99223953 0.5548226  0.38053943]
 [0.40288775 0.91644086 0.9413973 ]
 [0.54015904 0.46508984 0.4725572 ]] <class 'numpy.ndarray'>


In [22]:
#np.random.rand(5,6)*100 - 5x6 array of random floats between 0-100
p6 = np.random.rand(6,3)*100 
print(p6,type(p6))

[[95.82391353 80.26474584 75.39230807]
 [89.63423997 66.3224118  28.75733502]
 [54.92254898 75.28280543 45.40221879]
 [ 5.16551306 61.17078543 87.44294441]
 [87.60975233 99.73537763 37.45779825]
 [63.51283417  6.65910363 25.33370846]] <class 'numpy.ndarray'>


In [23]:
#np.random.randint(25,size=(2,3)) - 2x3 array with random ints between 0-24
p7 = np.random.randint(25,size=(2,3))
print(p7,type(p7))

[[ 8 21 19]
 [17  6  2]] <class 'numpy.ndarray'>


In [24]:
marks = [7, 8, 9, 9, 2, 1, 1, 5, 4, 5]

In [25]:
# 1D numpy array
n1 = np.array(marks, dtype=np.int16)

In [26]:
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)   # data type

[7 8 9 9 2 1 1 5 4 5]
<class 'numpy.ndarray'>
1
(10,)
int16


In [27]:
# vectorized computation
corrected_marks = n1 + 1
print(n1)
print(corrected_marks)
print(type(corrected_marks))

# sq = n1 ** 2
# print(sq)
# print(sq / 2)
# print(type(sq))

[7 8 9 9 2 1 1 5 4 5]
[ 8  9 10 10  3  2  2  6  5  6]
<class 'numpy.ndarray'>


In [28]:
# indexing
print(n1)
print(n1[0])
print(n1[-1])
print(n1[-2])
print(n1[[0, 2]])
na = n1[[0, -1, -2]]
print(type(na))
print(na)

[7 8 9 9 2 1 1 5 4 5]
7
5
4
[7 9]
<class 'numpy.ndarray'>
[7 5 4]


In [29]:
# slicing
print(n1)
first_three = n1[:3]
print(first_three)
print(type(first_three))
print(n1[-3:])

[7 8 9 9 2 1 1 5 4 5]
[7 8 9]
<class 'numpy.ndarray'>
[5 4 5]


In [32]:
# filtering
print(n1)
gr_than_5= n1 > 5
print(gr_than_5)

gr_than_5 = n1[n1 > 5]
print(gr_than_5)

[7 8 9 9 2 1 1 5 4 5]
[ True  True  True  True False False False False False False]
[7 8 9 9]


In [36]:
# Find even marks  or odd marks greater than 5

print(n1)
nnn = (n1 % 2 == 0) | (n1 > 5)
print(nnn)
nn = n1[(n1 % 2 == 0) | (n1 > 5)]
print(nn)

[7 8 9 9 2 1 1 5 4 5]
[ True  True  True  True  True False False False  True False]
[7 8 9 9 2 4]


In [35]:
# aggregations
print(n1)
print(n1.sum())
print(n1.mean())
print(n1.max())
print(n1.min())
print(np.median(n1))
print(np.std(n1))
print(np.var(n1))

[7 8 9 9 2 1 1 5 4 5]
51
5.1
9
1
5.0
2.947880594596735
8.690000000000001


In [ ]:
#2-D arrays

In [37]:
pcm = [
    [67,99,100],
    [99, 100, 76],
    [90, 90, 100]
]

In [38]:
n1 = np.array(pcm, dtype=np.float16)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

[[ 67.  99. 100.]
 [ 99. 100.  76.]
 [ 90.  90. 100.]]
<class 'numpy.ndarray'>
2
(3, 3)
float16


In [6]:
# indexing
print(n1[0])
print(n1[0][1]) # do not do this way in 2D list
print(n1[0,1])
print(n1[2,0])  # Physics marks of 3rd student
print(n1[-1,1]) # Chemistry marks by last student
print(n1[[0, -1]])
print(n1[[0, -1], 1]) # Chemistry marks of first and last student

[ 67.  99. 100.]
99.0
99.0
90.0
90.0
[[ 67.  99. 100.]
 [ 90.  90. 100.]]
[99. 90.]


In [39]:
# slicing
print(n1)
print(n1[-2:])
print(n1[-2:, 1:]) # chem and maths marks of last two students
print(n1[:2,:2])# marks scored in Phy and chem for first 2 students
print(n1[[0,-1],1:])# chem and maths by 1st and last student

[[ 67.  99. 100.]
 [ 99. 100.  76.]
 [ 90.  90. 100.]]
[[ 99. 100.  76.]
 [ 90.  90. 100.]]
[[100.  76.]
 [ 90. 100.]]
[[ 67.  99.]
 [ 99. 100.]]
[[ 99. 100.]
 [ 90. 100.]]


In [7]:
print(n1)
# aggregations
mean_marks = n1.mean(axis=0) # Mean alon axis 0 that is subject wise average
print(mean_marks)
print(type(mean_marks))
print(n1.sum(axis=1))

#std dev of the phy and math marks of last two students of the class
phy_n_math = n1[-2:, [0, 2]]
print(phy_n_math)
std_phy_math = np.std(phy_n_math, axis=0)
print(std_phy_math)

[[ 67.  99. 100.]
 [ 99. 100.  76.]
 [ 90.  90. 100.]]
[85.3 96.3 92. ]
<class 'numpy.ndarray'>
[266. 275. 280.]
[[ 99.  76.]
 [ 90. 100.]]
[ 4.5 12. ]


In [40]:
n1 = np.arange(30)
n1 = np.array([0, 1, 3, 5, -9, -34, 2, 7, 98, 97, 54, -23, 123, -67, 78, 98, 3, 0, 72, 723])
print(n1)
print(type(n1))

print(np.arange(5, 21))

[  0   1   3   5  -9 -34   2   7  98  97  54 -23 123 -67  78  98   3   0
  72 723]
<class 'numpy.ndarray'>
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
n2 = np.arange(9).reshape((3,3))
print(n2)
n35 = np.arange(15).reshape((3,5))
print(n35)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
n3 = n2.T
print(n3)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
